#!/bin/bash
#
# Kana Keyboard tr
#
if [[ $# = 0 ]] ; then
  KKINPUT=$( cat - )
else
  KKINPUT=$@
  1 #!/bin/bash↲
fi
#
echo $KKINPUT | tr '!-z' 'ぬふあうえおゃゅょけれねほるめわぬふあうえおやゆよけれねほるめ゜ちこそしいはきくにまのりもみらせたすとかなひてさんつ゜ーむへろ｀ちこそしいはきくにまのりもみらせたすとかなひてさんつ'
#
unset KKINPUT
#EOF
